- defaults:
    link:
      relink: true

- link:
    ~/.config/nvchad/nvim:
      path: nvchad
      create: true
    ~/.config/nvchad/.gitconfig: gitconfig
    ~/.local/bin/nn:
      path: bin/nn
      create: true
