- if:
    # check for dnf
    cond: "[ -f /usr/bin/dnf ]"
    met:
      - omnipkg:
          - install:
              # nvim dependencies
              - compat-lua-libs
              - libtermkey
              - libtree-sitter
              - libvterm
              - luajit
              - luajit2.1-luv
              - msgpack
              - unibilium
              - xsel

      - shell:
          # install nvim from github
          # EPEL repo does not have latest version
          - command: if [ ! -d ~/.local/share/nvim-linux64 ]; then curl -L https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz | tar -xz && mkdir -p ~/.local/share && mv nvim-linux64 ~/.local/share/nvim-linux64; fi
            stdin: false
            stdout: true
            stderr: true
            description: Install nvim
            quiet: false

      - link:
          ~/.local/bin/nvim:
            path: ~/.local/share/nvim-linux64/bin/nvim
            create: true
            relink: true

    unmet:
      # for other distros (not dnf)
      - omnipkg:
          - install:
              - [neovim, nvim]

              # should be in AUR
              - ghq
              - [rsc_2fa, 2fa]

- omnipkg:
    - install:
        # for development
        - pyenv
        - npm
        - luarocks
        - ripgrep

        - docker
        - docker-buildx
        - docker-compose
        - lazydocker
