- omnipkg:
    - upgrade

- omnipkg:
    - install:
        # common
        - tar
        - openssh
        - zsh
        - tmux

- if:
    # check for dnf
    cond: "[ -f /usr/bin/dnf ]"
    met:
      - omnipkg:
          - install:
              - util-linux-user # for chsh
              - yum-utils # for repoquery -q --installed --whatrequires python3

              - glibc-locale-source # for localedef
              - glibc-langpack-en # for localedef

              - epel-release # Extra Packages for Enterprise Linux
              # - xz # for Nix install

          - shell:
              - [dnf copr enable -y atim/lazygit, Enable copr lazygit]

# change shell
- shell:
    - ["chsh -s /usr/bin/zsh || true", Change shell to zsh]
    - [
        "localedef -i en_US -c -f UTF-8 en_US.UTF-8 || true",
        Set locale to en_US.UTF-8,
      ]

- omnipkg:
    - install:
        # Common packages for all distros after EPEL enabled
        - htop
        - zoxide
        - lazygit
        - mcfly
#
# TODO: Nix Package Manager

# - shell:
#     - [
#         bash <(curl -L https://nixos.org/nix/install) --no-daemon --no-modify-profile,
#         Install Nix,
#       ]
# - nixenv:
#     - packages:
#         - nixpkgs.htop
#         - nixpkgs.zoxide
#
#         - nixpkgs.ghq
#         - nixpkgs.2fa
#
#         - nixpkgs.neovim
#         - nixpkgs.python3
#         - nixpkgs.lazygit
#         - nixpkgs.luarocks
#         - nixpkgs.npm
#         - nixpkgs.ripgrep
