- omnipkg:
    - install:
        - neovim

    # install mcfly
    - shell:
        - [curl -LSfs https://raw.githubusercontent.com/cantino/mcfly/master/ci/install.sh | sh -s -- --git cantino/mcfly]
